package com.jizhiwei.student.bean;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_id
     *
     * @mbg.generated Wed Aug 22 18:02:22 CST 2018
     */
    private Integer tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_name
     *
     * @mbg.generated Wed Aug 22 18:02:22 CST 2018
     */
    private String tName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_age
     *
     * @mbg.generated Wed Aug 22 18:02:22 CST 2018
     */
    private Integer tAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_email
     *
     * @mbg.generated Wed Aug 22 18:02:22 CST 2018
     */
    private String tEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_id
     *
     * @return the value of teacher.t_id
     *
     * @mbg.generated Wed Aug 22 18:02:22 CST 2018
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_id
     *
     * @param tId the value for teacher.t_id
     *
     * @mbg.generated Wed Aug 22 18:02:22 CST 2018
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_name
     *
     * @return the value of teacher.t_name
     *
     * @mbg.generated Wed Aug 22 18:02:22 CST 2018
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_name
     *
     * @param tName the value for teacher.t_name
     *
     * @mbg.generated Wed Aug 22 18:02:22 CST 2018
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_age
     *
     * @return the value of teacher.t_age
     *
     * @mbg.generated Wed Aug 22 18:02:22 CST 2018
     */
    public Integer gettAge() {
        return tAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_age
     *
     * @param tAge the value for teacher.t_age
     *
     * @mbg.generated Wed Aug 22 18:02:22 CST 2018
     */
    public void settAge(Integer tAge) {
        this.tAge = tAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_email
     *
     * @return the value of teacher.t_email
     *
     * @mbg.generated Wed Aug 22 18:02:22 CST 2018
     */
    public String gettEmail() {
        return tEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_email
     *
     * @param tEmail the value for teacher.t_email
     *
     * @mbg.generated Wed Aug 22 18:02:22 CST 2018
     */
    public void settEmail(String tEmail) {
        this.tEmail = tEmail == null ? null : tEmail.trim();
    }
}